<a href="https://colab.research.google.com/github/Impossiblepretext/Experiment_No.8/blob/main/Experiment_No_8_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Experiment No.8

Title: Tools for EDA- NumPy

Name: Vibhas Shukla

PRN: 25070123164

Batch: F.Y Entc A1

In [6]:
import numpy as np
a=np.array([10,20,30,40])
b=np.array([[1,2,3],[4,5,6]])
print(a)
print(b)

[10 20 30 40]
[[1 2 3]
 [4 5 6]]


In [10]:
a.ndim


1

In [9]:
b.ndim

2

In [11]:
a.shape

(4,)

In [12]:
b.shape

(2, 3)

In [13]:
a.dtype

dtype('int64')

In [14]:
b.dtype


dtype('int64')

In [15]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.eye((2))

array([[1., 0.],
       [0., 1.]])

In [21]:
np.arange(10,25,5)

array([10, 15, 20])

In [23]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [24]:
a+5

array([15, 25, 35, 45])

In [25]:
a*2

array([20, 40, 60, 80])

In [26]:
np.mean(a)

np.float64(25.0)

In [27]:
np.median(a)

np.float64(25.0)

In [28]:
np.max(a)

np.int64(40)

In [29]:
np.min(a)

np.int64(10)

In [30]:
np.sum(a)

np.int64(100)